### ISSUE TITLE
Add support for Discord Slash commands

### ISSUE THREAD

**Issue by notsniped** [notsniped/discord-snipe-bot#4]
### Reason
This is to adjust to the new API restrictions set by discord, that all new bots should adopt the slash commands feature by the end of the month.
### Tasks
- [x] Add the discord-slash library
- [x] Initialize the library with the Discord client
- [x] Make replicas of the `snipe` and `editsnipe` commands in slash 
- [ ] Debug
